# Generated by Django 5.2.1 on 2025-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Mohamadreza', max_length=100),
        ),
    ]
